# Generated by Django 3.2.2 on 2022-11-29 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gettariff',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='tariff',
            name='month',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='tariff',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
