# Generated by Django 3.2.2 on 2022-12-14 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pictures',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
