# Generated by Django 3.2.2 on 2022-11-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20221129_0647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gettariff',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
