# Generated by Django 3.2.2 on 2022-11-29 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_gettariff_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='gettariff',
            name='is_approve',
            field=models.BooleanField(default=False),
        ),
    ]
