version: "3.9"

services:

  redis:
    image: redis:alpine
    restart: always
    ports:
    - "6379:6379"

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      DATABASE_HOSTNAME: ${DB_HOST}
    ports:
      - "5432:5432"
    volumes:
      - "./postgres:/var/lib/postgresql/data"

  app:
    build: .
    volumes:
      - .:/rentit
    ports:
    - "8000:8000"
    command: bash -c "python manage.py collectstatic --no-input && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  celery:

    restart: always
    build: .
    command: celery -A rentit worker -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  celery-beat:

    restart: always
    build: .
    command: celery -A rentit beat -l info
    volumes:
      - .:/app
    depends_on:
      - redis

  flower:
    restart: always
    build: .
    ports:
      - 5555:5555
    command: celery -A rentit flower

