# Generated by Django 3.2.2 on 2022-12-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detailcategory',
            name='detail',
            field=models.ManyToManyField(blank=True, to='products.Detail'),
        ),
    ]
