# Generated by Django 3.2.2 on 2022-12-03 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20221203_1226'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pictures',
            name='name',
        ),
    ]
