# Generated by Django 3.2.2 on 2022-12-03 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_pictures_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WishList',
        ),
    ]
