# Generated by Django 3.2.2 on 2022-12-13 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_productsubcategory_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('som', 'some'), ('dollar', 'dollar')], default='som', max_length=255, null=True),
        ),
    ]
