# Generated by Django 3.2.2 on 2022-12-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_auto_20221213_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='currency',
            field=models.CharField(choices=[('some', 'some'), ('dollar', 'dollar')], default='some', max_length=255, null=True),
        ),
    ]
