# Generated by Django 3.2.2 on 2023-02-21 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_auto_20221214_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='picture1',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture10',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture2',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture3',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture4',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture5',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture6',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture7',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture8',
        ),
        migrations.RemoveField(
            model_name='product',
            name='picture9',
        ),
    ]
